export const SAGA_GETMENUTREE='SAGA_GETMENUTREE'; //权限树获取
export type SAGA_GETMENUTREE=typeof SAGA_GETMENUTREE; 

export const SAGA_GETMENULIST='SAGA_GETMENULIST'; //权限
export type SAGA_GETMENULIST=typeof SAGA_GETMENULIST; 