export const SAGA_GETMENUTREE='SAGA_GETMENUTREE'; // 权限树获取
export type SAGA_GETMENUTREE=typeof SAGA_GETMENUTREE; 

export const SAGA_GETMENULIST='SAGA_GETMENULIST'; // 权限
export type SAGA_GETMENULIST=typeof SAGA_GETMENULIST; 

export const SAGA_GET_USER_LIST='SAGA_GET_USER_LIST'; 
export type SAGA_GET_USER_LIST=typeof SAGA_GET_USER_LIST; 

export const SAGA_GET_USER_INFO='SAGA_GET_USER_INFO'; 
export type SAGA_GET_USER_INFO=typeof SAGA_GET_USER_INFO; 